#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

ipmitool=/usr/bin/ipmitool

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <sub command> <host> <address>" >&2
    exit 1
fi

if [ -z ${IPMI_USERNAME:-} ] || [ -z ${IPMI_PASSWORD:-} ]; then
    echo "IPMI_USERNAME or IPMI_PASSWORD environment variables not found" >&2
    exit 1
fi

username=$IPMI_USERNAME
sub_command=$1
host=$2
new_address=$3

echo "[$host] "
$ipmitool -I lanplus -E -H "$host" -U "$username" lan set 1 "$sub_command" "$new_address"

# vim: tabstop=4 shiftwidth=4 expandtab:
