#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

ipmitool=/usr/bin/ipmitool

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <host> <ipmi commands>" >&2
    exit 1
fi

if [ -z ${IPMI_USERNAME:-} ] || [ -z ${IPMI_PASSWORD:-} ]; then
    echo "IPMI_USERNAME or IPMI_PASSWORD environment variables not found" >&2
    exit 1
fi

username=$IPMI_USERNAME
host=$1

shift

echo "[$host] "
$ipmitool -I lanplus -E -H "$host" -U "$username" "$@"

# vim: tabstop=4 shiftwidth=4 expandtab:
